[tool.poetry]
name = "openai-api"
version = "0.0.1"
description = "API USING GPT MODEL"
authors = ["Juan Calvo <juan.calvo@datatonic.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = "^0.1"
google-cloud-aiplatform = ">=1.35.0"



[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.15"
fastapi = "^0.104.0"
sse-starlette = "^1.6.5"

[tool.langserve]
export_module = "openai_api"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "Datatonic"
integrations = ["OpenAI", "Google"]
tags = ["vectordbs"]

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
